# Generated by Django 3.2.8 on 2021-10-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('nom_epouse', models.CharField(max_length=200, null=True)),
                ('nombre_enfant', models.IntegerField(max_length=200, null=True)),
                ('sexe', models.CharField(choices=[('masculin', 'masculin'), ('femmin', 'femmin')], max_length=200, null=True)),
                ('adresse_physique', models.CharField(max_length=200, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('sexe', models.CharField(choices=[('masculin', 'masculin'), ('femmin', 'femmin')], max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('adresse_physique', models.CharField(max_length=200, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
