# Generated by Django 3.2.8 on 2021-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_auto_20211106_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nombre_medecin',
            field=models.IntegerField(null=True),
        ),
    ]
