# Generated by Django 3.2.8 on 2021-11-29 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_remove_personne_type_de_service'),
        ('specialiste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialiste',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.service'),
        ),
    ]
