# Generated by Django 3.2.8 on 2021-11-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='dossier',
            new_name='personne',
        ),
    ]
