# Generated by Django 3.2.8 on 2021-11-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_remove_personne_type_de_service'),
        ('medecin', '0002_rename_dossier_medecin_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='type_de_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.service'),
        ),
    ]
