# Generated by Django 3.2.8 on 2021-11-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_medecin_type_de_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='type_de_service',
            new_name='service',
        ),
    ]
